# Generated by Django 3.1.5 on 2021-01-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasstations',
            fields=[
                ('gasstationid', models.PositiveSmallIntegerField(db_column='gasStationID', primary_key=True, serialize=False)),
                ('gasstationlat', models.DecimalField(blank=True, db_column='gasStationLat', decimal_places=7, max_digits=10, null=True)),
                ('gasstationlong', models.DecimalField(blank=True, db_column='gasStationLong', decimal_places=7, max_digits=10, null=True)),
                ('fuelcompid', models.IntegerField(db_column='fuelCompID')),
                ('fuelcompnormalname', models.CharField(db_column='fuelCompNormalName', max_length=45)),
                ('gasstationowner', models.CharField(db_column='gasStationOwner', max_length=128)),
                ('ddid', models.CharField(db_column='ddID', max_length=10)),
                ('ddnormalname', models.CharField(db_column='ddNormalName', max_length=45)),
                ('municipalityid', models.CharField(db_column='municipalityID', max_length=10)),
                ('municipalitynormalname', models.CharField(db_column='municipalityNormalName', max_length=45)),
                ('countyid', models.CharField(db_column='countyID', max_length=10)),
                ('countyname', models.CharField(db_column='countyName', max_length=64)),
                ('gasstationaddress', models.CharField(blank=True, db_column='gasStationAddress', max_length=255, null=True)),
                ('phone1', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'gasstations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.IntegerField(db_column='orderID', primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('when', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pricedata',
            fields=[
                ('productid', models.AutoField(db_column='productID', primary_key=True, serialize=False)),
                ('fueltypeid', models.PositiveIntegerField(db_column='fuelTypeID')),
                ('fuelsubtypeid', models.PositiveIntegerField(db_column='fuelSubTypeID')),
                ('fuelnormalname', models.CharField(db_column='fuelNormalName', max_length=64)),
                ('fuelname', models.CharField(db_column='fuelName', max_length=128)),
                ('fuelprice', models.DecimalField(db_column='fuelPrice', decimal_places=3, max_digits=4)),
                ('dateupdated', models.DateTimeField(blank=True, db_column='dateUpdated', null=True)),
                ('ispremium', models.IntegerField(blank=True, db_column='isPremium', null=True)),
            ],
            options={
                'db_table': 'pricedata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
